### ISSUE TITLE
Allow less strict (date-based) monitoring requirement deadlines

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogetherCMS#558]

**Comment by LarsKemmann** [comment]
Don't remove the time component but only use the date component for overdue calculations

**Comment by Debi-AVL** [comment]
I think this is the same issue I wanted to comment on. I'd love it if the fixed dates on required tasks such as "check in with X family" could be more flexible such as a date range. If a parent ally needs to meet with a parent during the week of July 4-10, it would be helpful to choose the date it happened rather than say it happened on the specific date indicated (such as July 5) and then have to explain in the notes that it was actually on July 6th. I hope that makes sense!

**Comment by LarsKemmann** [comment]
> I think this is the same issue I wanted to comment on. I'd love it if the fixed dates on required tasks such as "check in with X family" could be more flexible such as a date range. If a parent ally needs to meet with a parent during the week of July 4-10, it would be helpful to choose the date it happened rather than say it happened on the specific date indicated (such as July 5) and then have to explain in the notes that it was actually on July 6th. I hope that makes sense!

This is definitely related, but I almost think we might want to create a specific policy that lets this be represented more precisely in the system. Right now, the policy is basically "each check-in is due within 7 days from the last check-in" rather than "check-in is due sometime during this 7-day week and the next check-in is due during the following 7-day week, regardless of when in the first week you actually checked in". Can you confirm if you actually want your policy to be the latter?

**Comment by Debi-AVL** [comment]
Yes - the latter policy works better than a specific day for things like Family Care Supervision, Parent Ally Meetings, Updating Parent Goals, etc. The only one where a hard and fast date would be needed is for the 48 hour visit and host family check-ins when a hosting is taking place.

Debi Forester
Family Care Coordinator | Alongside Families
828-333-9520
***@***.***
alongsidefamilies.org<http://www.alongsidefamilies.org>
________________________________
